# Generated by Django 5.1.7 on 2025-03-23 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro_api_v1', '0003_student_id_teacher_id_alter_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gympro_api_v1.teacher'),
        ),
    ]
