# Generated by Django 5.1.7 on 2025-03-23 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro_api_v1', '0005_category_exercise_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weekday',
            field=models.CharField(default='monday', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serie',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='gympro_api_v1.exercise'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
