# Generated by Django 5.1.7 on 2025-03-23 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro_api_v1', '0006_alter_exercise_category_exercise_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='gympro_api_v1.exercise'),
        ),
    ]
