# Generated by Django 5.1.7 on 2025-03-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro_api_v1', '0007_alter_serie_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='repetitions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serie',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
