# Generated by Django 5.1.7 on 2025-03-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro_api_v1', '0008_alter_serie_repetitions_alter_serie_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serie',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
