# Generated by Django 5.1.7 on 2025-03-25 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro_api_v1', '0009_alter_serie_repetitions_alter_serie_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gympro_api_v1.student'),
            preserve_default=False,
        ),
    ]
