# Generated by Django 5.1.7 on 2025-03-27 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro_api_v1', '0010_exercise_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=0)),
                ('exercises', models.ManyToManyField(related_name='workouts', to='gympro_api_v1.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gympro_api_v1.student')),
            ],
        ),
    ]
