# Generated by Django 5.1.7 on 2025-03-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro_api_v1', '0012_remove_workout_exercises_workoutexercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='endDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='startDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
