# Generated by Django 5.1.7 on 2025-03-29 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro_api_v1', '0013_alter_workout_enddate_alter_workout_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fullName',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='fullName',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weekday',
        ),
        migrations.AddField(
            model_name='student',
            name='picture_url',
            field=models.CharField(default='https://i.stack.imgur.com/y9DpT.jpg', max_length=400),
        ),
        migrations.AddField(
            model_name='teacher',
            name='picture_url',
            field=models.CharField(default='https://i.stack.imgur.com/y9DpT.jpg', max_length=400),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gympro_api_v1.category'),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gympro_api_v1.student')),
            ],
        ),
        migrations.CreateModel(
            name='DayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gympro_api_v1.category')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gympro_api_v1.day')),
            ],
        ),
    ]
