# Generated by Django 5.1.7 on 2025-03-30 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro_api_v1', '0014_category_rename_fullname_student_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='daycategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='daycategory',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExerciseDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gympro_api_v1.day')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gympro_api_v1.exercise')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='DayCategory',
        ),
    ]
