# Generated by Django 5.1.7 on 2025-03-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gympro_api_v1', '0015_remove_exercise_category_remove_daycategory_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='student',
        ),
    ]
