# Generated by Django 5.1.7 on 2025-03-30 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gympro_api_v1', '0016_remove_exercise_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='exercise',
        ),
        migrations.AddField(
            model_name='serie',
            name='exercise_day',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gympro_api_v1.exerciseday'),
            preserve_default=False,
        ),
    ]
